### PR TITLE
Adjusts several options to resolve syntax or other issues

### PR DESCRIPTION
**Pull request by aurorawillow**
Pull request to accomplish the following:

- Update gpg check to remove '#' from listing 
- Update /etc/sudoers.d/ configs 
- TMOUT variable does not need to be read-only for scoring

Reasoning is in each commit message.

### CODE REVIEW

**Comment by aurorawillow** [comment]
Adds updates to use logfile instead of iolog_files commit.

**Comment by aurorawillow** [comment]
Adjusts ntp pool to remove continental time server pools as it is not needed.

**Review by jbertozzi — CHANGES_REQUESTED** [review]
Hi,

The file name is harcoded (could be something like {{ cis_rhel8_sudo_file }} with default value to "cis") but it does not require the user to exist.

Other changes make sense, thank you. :)

**Comment by aurorawillow** [comment]
@jbertozzi Hey sorry - forgot another change! 🤣 

Gotcha on the file name, but the specific ansible task doesn't have anything to do with the filename does it? Maybe I'm not following what you mean here.

Edit: I think I understand. Let me adjust.

**Comment by aurorawillow** [comment]
@jbertozzi Commits ab8fffd & 15d6da8 should address your concern on the /etc/sudoer.d/ configs.

**Comment by aurorawillow** [comment]
Maybe I should've made this a draft PR...apologies!

**Comment by aurorawillow** [comment]
Hey @jbertozzi , I think I've made all changes I need to make for now. However, I am not sure what the Travis Tests are failing on. When I re-run the role on a test system I have, I have no issues.

**Comment by jbertozzi** [comment]
Hello,

Thanks for your work.

I have added one commit to yours, in order to be consistent regarding the sudoers config file.

I'd like to have all the configuration files related to this role in file easily identifiable (i.e. named "cis" by default: /etc/sudoers.d/cis, /etc/cron.d/cis...).

**Comment by jbertozzi** [comment]
> However, I am not sure what the Travis Tests are failing on. 

Seems like the file module used with `state: touch` is not idempotent.

`state: file` will not create the file.

I have added two templates file to workaround for 5.1.8.

**Pull request merged**
